### PR TITLE
Py3.10, Bullseye && PyUpgrade cleanup

### LINKED ISSUE #404: Remove explicit unicode string typing
There are still lots of code parts where the `u"string"` notation is used, even though it is unnecessary in python 3.

We should remove the "u" prefixes in the whole project.

### PR DESCRIPTION
**Pull request by lukasjuhrich**
- [x] upgrade to py3.10
- [x] upgrade to bullseye
- [x] setup && run pyupgrade
- [x] find workaround for failing `uwsgi` wheel build
- [x] find out why `npm` executable does not exist
- [x] mark cleanup commits as [ignored revisions](https://github.com/agdsn/pycroft/issues/404#issuecomment-684980681)
- [x] see what comes of [pycharm bug PY-51696](https://youtrack.jetbrains.com/issue/PY-51696)
- [x] remove unused imports (e.g. lots of `from typing import` statements are now superfluous)

Fixes #404

### CODE REVIEW

**Comment by lukasjuhrich** [comment]
```shell
docker-compose build base
docker run -ti --rm --entrypoint=/bin/bash agdsn/pycroft-dev
/opt/pycroft/venv/bin/pip --no-cache -v wheel $uwsgi_qualifier
```
Okay, now do the following:
- with `$uwsgi_qualifier` as `uwsgi` or `git+git://github.com/lukasjuhrich/uwsgi.git@c99202887bb7fa05e8ae4ed1f6403bb648923099#egg=uwsgi`, the build breaks frequently (start a new docker container on each try)
- wich `$uwsgi_qualifier` as `git+git://github.com/lukasjuhrich/uwsgi.git@uwsgi-2.0#egg=uwsgi`, it works

Between these commits, the following changed:
https://github.com/lukasjuhrich/uwsgi/compare/c99202887bb7fa05e8ae4ed1f6403bb648923099...lukasjuhrich:uwsgi-2.0?expand=1

```diff
--- a/uwsgiconfig.py
+++ b/uwsgiconfig.py
@@ -117,7 +117,7 @@ def thread_compiler(num):
             print_lock.acquire()
             print_compilation_output("[thread %d][%s] %s" % (num, GCC, objfile), "[thread %d] %s" % (num, cmdline))
             print_lock.release()    
-            ret = os.system(cmdline)
+            ret = subprocess.call(cmdline, shell=True)
             if ret != 0:
                 os._exit(1)
         elif cmdline:
```
I don't have the slightest clue how this would change anything

**Comment by lukasjuhrich** [comment]
@ibot3 requesting you as reviewer to reproduce [the pycharm bug](https://youtrack.jetbrains.com/issue/PY-51696)

**Comment by ibot3** [comment]
The package list is loading for me with pycharm 2021.2.2 and 2021.2.3.
The `+` button is greyed out, but this is also the case with other docker-compose interpreters.

**Comment by lukasjuhrich** [comment]
Have you verified that the image has been re-built (i.e., `/opt/pycroft/venv/bin/python -V` gives `3.10.0`)?

**Pull request merged**
