### PR TITLE
Update OpenSearch description

### PR DESCRIPTION
**Pull request by FestplattenSchnitzel**
- Add xmlns:moz namespace
- Add InputEncoding
- Add Image
- Fix typo

### CODE REVIEW

**Comment by mmarx** [comment]
> Add xmlns:moz namespace

why, though? No tags from the `moz` namespace are actually used in the description.

**Comment by FestplattenSchnitzel** [comment]
> why, though?

Currently, it's not possible to add the Pycroft OpenSearch description.  Since almost all OSDs declare the xmlns:moz namespace, I guessed that might be the reason why it's not working currently.

**Comment by mmarx** [comment]
It should only be required if you add the `moz:SearchForm` tag (shouldn't hurt to have it even if it's not needed, though). Another problem I can see is that the `Url` tag doesn't seem to allow a `method` attribute: https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#the-url-element

**Comment by FestplattenSchnitzel** [comment]
`Url` with `method` attribute is used by Wikipedia view-source:https://de.wikipedia.org/w/opensearch_desc.php and works for me.

**Comment by lukasjuhrich** [comment]
Perhaps you can test these hypotheses with a local nginx server to alleviate us from guesswork

**Comment by FestplattenSchnitzel** [comment]
> Currently, it's not possible to add the Pycroft OpenSearch description.

OK, the reason for this was completely different: when adding an OSD, Firefox seems to make an isolated request unaware of any authentication (cookies, basic auth).
With the whole https://pycroft.agdsn.de/ deployment behind a basic auth, it ran into an HTTP 401 every time.

With https://git.agdsn.de/AGDSN/Ansible/-/merge_requests/195 , https://pycroft.agdsn.de/static/xml/opensearch.en.415ab08a4bb518e6a23d4fbf16e3c00b.xml has been excluded from basic auth, fixing the error.

**Pull request closed without merging**
