### PR TITLE
Gerok importer

### PR DESCRIPTION
**Pull request by strebbin**
Adds an Importer for legacy-users of the dormitory Gerokstraße witch uses the legacy user management software "nvtool"

Like in the other legacy importer the traffic data is currently not imported .

### CODE REVIEW

**Comment by lukasjuhrich** [comment]
Please, do not merge an upstream branch back into your feature branch, especially if the changes are mostly orthogonal. Do a clean rebase instead, if the branch is about to be merged.

**Comment by strebbin** [comment]
I have removed the merge and rebased my changes instead.

**Comment by lukasjuhrich** [comment]
I added a few changes and will try to test the incremental import on Wednesday, but it looks good so far.

**Comment by strebbin** [comment]
I checked and corrected the function of this importer so it runs correctly after the Wu/Legacy-Importer.

**Pull request merged**
