### PR TITLE
Edit payment reminder template

### PR DESCRIPTION
**Pull request by LukasGibeh**

### CODE REVIEW

**Review by gehinz — APPROVED** [review]
Passt so

**Review by marcelb98 — APPROVED** [review]

**Review by jnsga — APPROVED** [review]
für weniger Tickets 👍

**Comment by lukasjuhrich** [comment]
`master` is the wrong target.
Just adding this comment as a placeholder before someone closes this PR prematurely, I will take care of any necessary rebasing.

**Comment by lukasjuhrich** [comment]
Thanks a lot @LukasGibeh!

**Comment by LukasGibeh** [comment]
Hi @lukasjuhrich 

having `master` as the target was actually the intention of @gehinz and me to have the text deployed at the latest for the next mail distribution.

**Comment by lukasjuhrich** [comment]
That's not quite how our deployment model works.
The master branch is coupled with the guarantee that wherever `master` points to corresponds to what is currently deployed.
Partly, the reason for that is the absence of a versioning system.
Anyway, the only scenario in which `master` should be forwarded is when you actually do a deployment.

The next one should happen now or in the next few days.

**Pull request merged**
